### ISSUE TITLE
Base de datos descargable

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#104]
@elcoruco no estoy muy seguro pk no lo he podido probar más veces mandando encuestas, pero cuando descargas las preguntas de opción múltiple varias te aparecen ahora todas las opciones posibles que pusiste, me parece que es por que automáticamente, las preguntas de checkbox te aparecen todas seleccionadas. Y si por ejemplo, dedibo a una regla te saltas la pregunta, entonces  se quedan como si todas hubieran sido seleccionadas.

**Comment by elcoruco** [comment]
![captura de pantalla 2016-05-04 a las 10 46 23 a m](https://cloud.githubusercontent.com/assets/3756555/15019904/7940315e-11e5-11e6-86fa-5f8a39854478.png)


El detalle, es que si ya contestaste la encuesta con una clave, las respuestas que ya llenaste, se guardan, y aparecen de nuevo, aunque salgas y entres a la encuesta varias veces, y sigas distintos caminos. (Siempre y cuando, sea la misma clave de usuario)


Si generas una nueva clave de usuario, no se pre-llena ninguna pregunta.
