### ISSUE TITLE
Para el envío de encuestas, te quería preguntar si estos días me puedes liberar una cierta cantidad de correos para enviar las encuestas de conacyt e imjuve

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#105]
@elcoruco son entre 1500 y 2000 correos entre ambas.

**Comment by elcoruco** [comment]
ya no hay límite de correos. [ obviamente el límite de mi tarjeta de crédito, porque no han sacado una cuenta de mailgun... ]
