### ISSUE TITLE
Cancelar en cuesta

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#107]
@elcoruco En administradores no se tiene que cambiar mostrar por cancelar, ya que la funcionalidad es distinta a funcionarios publicos. En admi inistradores controlas la visibilidad en la pagina, pero no cambias el status (se queda la encuesta "en curso"), en cambio, cuando se cancela en funcionarios públicos se regresa a estar oculta.

**Comment by hugovom** [comment]
@Victordeleon :bowtie:

**cancelar:**
- tr. Anular, dejar sin validez, especialmente documentos legales: le han cancelado el permiso de conducir. 
- Suspender lo que se tenía previsto: han cancelado todos los vuelos. 
- Saldar, pagar una deuda: ya he cancelado la última letra del coche.

**mostrar:**
- tr. Exponer algo a la vista, señalarlo para que se vea: el vendedor mostraba su género. 
- Explicar, dar a conocer mediante una explicación: muéstrame en qué me he equivocado. 
- Indicar, presentar: nos mostró el camino. 
- Manifestar una cualidad o un estado de ánimo: mostró su decepción por nuestra derrota. prnl. 
- Darse a conocer de alguna manera, comportarse, manifestarse: hoy se muestra muy contento. Irreg. Se conj. como[fjcontar.

**Comment by elcoruco** [comment]
regresó ocultar en lugar de cancelar.
