### ISSUE TITLE
Acomodo de preguntas en la edición de encuestas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#108]
@elcoruco ¿Hay alguna forma de acomodar el orden de las preguntas fuera de el orden en que se meten?

La duda es porque cree una encuesta desde un archivo excel, pero como este no tiene formato para agregar texto, traté de acomodarlo moviendo la sección de las preguntas. El problema es que el texto, dentro de cada sección, se termina acomodando abajo de las preguntas, lo que no te permite utilizarlo para manejar subtítulos para las preguntas.

**Comment by hugovom** [comment]
@Victordeleon esto no es posible, saludos
