### ISSUE TITLE
Ramo y Programa presupuestario en Edición de Encuestas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#109]
@elcoruco En la sección de encuestas, el ramo se está jalando a la Presidencia de la República (Ramo 2), aunque este no tiene programa presupuestarios con link al ptp. Revisé el json para quitarlo pero no está en el de programas, por lo que me parece que se lo está jalando de algún otro lado.

**Comment by elcoruco** [comment]
hay que borrarlo de ramos.js y ramos.json
