### ISSUE TITLE
Apartados Equipo y Participantes

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#113]
Aqui hace falta actualizar la vista de los logos de Equipo Tu Evaluas y Participantes Tu Evaluas:

Codigo:
`<div class="row">
					<div class="col-md-12">				
						<h3>Equipo <strong>Tú evalúas</strong></h3>
						<ul class="row">
							<p class="col-xs-4"><img src="img/presidencia_.png"><br><a href="http://www.gob.mx/presidencia/">Presidencia</a></p>
							<p class="col-xs-4"><img src="img/transparencia_presupuestaria_.png"><br><a href="http://www.transparenciapresupuestaria.gob.mx/">Transparencia<br>Presupuestaria</a></p>
							<p class="col-xs-4"><img src="img/shcp_.png"><a href="http://www.gob.mx/hacienda"><br>SHCP</a></p>
						</ul>
						<ul class="row">
							<p class="col-xs-2"></p>
							<p class="col-xs-4"><img src="img/crea_emp_.png"><br><a href="http://www.crea.org.mx/">CREA</a></p>
							<p class="col-xs-4"><img src="img/gobierno_facil_.png"><br><a href="http://gobiernofacil.com/">Gobierno Fácil</a></p>
						</ul>
					</div>
				</div>	
         		<div class="row">
					<div class="col-md-12">
						<h3>Participantes <strong>Tú evalúas</strong></h3>
						<ul class="row">
							<p class="col-xs-4"><img src="img/sedesol_.png"><br><a href="http://www.gob.mx/sedesol">SEDESOL</a></p>
							<p class="col-xs-4"><img src="img/prospera_.png"><br><a href="https://www.prospera.gob.mx/">PROSPERA</a></p>
							<p class="col-xs-4"><img src="img/inadem_.png"><br><a href="https://www.inadem.gob.mx/">INADEM</a></p>
						</ul>
						<ul class="row">
							<p class="col-xs-2"></p>
							<p class="col-xs-4"><img src="img/imjuve_.png"><br><a href="http://www.imjuventud.gob.mx/">IMJUVE</a></p>
							<p class="col-xs-4"><img src="img/conacyt_.png"><br><a href="http://www.conacyt.mx/">CONACYT</a></p>
						</ul>
					</div>
				</div>`

Antes:
![image](https://cloud.githubusercontent.com/assets/18603729/15027359/0653c312-1209-11e6-9ea4-56a457c6adb2.png)

Despues:
![image](https://cloud.githubusercontent.com/assets/18603729/15027387/1fde5afe-1209-11e6-9d32-904192d88f70.png)

**Comment by hugovom** [comment]
@julioaleman además de la imagen llevan el texto?

**Comment by julioaleman** [comment]
@hugovom si, victor me comento que le solicitaron que les pusieramos etiquetas a cada logo, cualquier duda comentalo con @Victordeleon

**Comment by hugovom** [comment]
@Victordeleon que lo comente contigo, se ve de la goma :bowtie:
