### ISSUE TITLE
Pregunta Abierta

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#114]
Screenshoot:
![image](https://cloud.githubusercontent.com/assets/18603729/15054838/08945d6e-12cf-11e6-9e60-7302bba1cb1f.png)

Codigo:
`<div class="bottom-buffer">
					<form role="form">
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label class="control-label">¿Deseas dejarnos algún comentario?</label>
									<textarea class="form-control" placeholder="" rows="3"></textarea>
								</div>
							</div>
						</div>
					</form>
				</div>`

**Comment by hugovom** [comment]
@julioaleman @Victordeleon de acuerdo con @elcoruco no podemos cambiar a textarea, permanecerá como input
