### ISSUE TITLE
Pregunta Opcion Multiple (Unica)

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#116]
Screenshoot:
![image](https://cloud.githubusercontent.com/assets/18603729/15055005/ed6541ce-12cf-11e6-9d54-860b17d54532.png)

Codigo:
`<div class="bottom-buffer">
					<form role="form">
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label class="control-label">¿Te gusta la encuesta?</label>
										<div class="radio">
											<label><input type="radio" name="radio-01" value="opcion-01" checked="checked"> Si</label><br>
											<label><input type="radio" name="radio-01" value="opcion-02" checked="checked"> No</label>
										</div>
								</div>
							</div>
						</div>
					</form>
				</div>`

**Comment by hugovom** [comment]
@julioaleman no es necesario el <br> … 
<img width="707" alt="screen shot 2016-05-05 at 11 32 16 p m" src="https://cloud.githubusercontent.com/assets/2445854/15064429/bfbf3208-1319-11e6-8c0e-1bee8f413feb.png">
