### ISSUE TITLE
En el botón “Crear Encuesta” eliminar columnas con el compilado de encuestas, aquí podrá el usuario comenzar a crear su encuesta nueva.

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#12]

**Comment by hugovom** [comment]
@elcoruco supongo que al crearse te debería de redirigir a la encuesta

**Comment by Victordeleon** [comment]
Yo proponía que aquí se colocan los recuadros que actualmente están en el costado izquierdo de mis encuestas... Lis de crear encuesta nueva, cargar encuesta desde csv y Carga tus propios resultados.
