### ISSUE TITLE
Agregar el buscador avanzado de la sección de resultados a la de Datos Abiertos

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#125]
@elcoruco con la misma funcionalidad, solo que también esté en la sección de datos abiertos.

**Comment by hugovom** [comment]
@Victordeleon esto no es viable $

**Comment by Victordeleon** [comment]
@hugovom @elcoruco sería exactamente la misma funcionalidad, solo que aplicada en la sección de Datos Abiertos. Para la búsqueda avanzada dentro de los portales de funcionario y administrador prácticamente me hicieron un copy paste de esta funcionalidad, no veo por que es inviable para la sección de Datos Abiertos.
