### ISSUE TITLE
Tanto para la previsualización, como para las encuestas enviadas, agregar botón que permita regresar a la sección anterior por si el que responde una encuesta se equivoco o quiere cambiar su encuesta

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#127]
@elcoruco 

![image](https://cloud.githubusercontent.com/assets/17733942/15089526/6e4e5334-13ca-11e6-9ee6-232562915853.png)

**Comment by elcoruco** [comment]
debido a ciertos detalles técnicos, se propone un botón para reiniciar encuesta. Arreglar este tipo de cambio en la encuesta es muy complicado.
