### ISSUE TITLE
Habilitar la posibilidad de agregar hipervínculos a las preguntas realizadas. 

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#128]
@elcoruco por ejemplo, si pides que te coloquen el ramo, que el que responda la encuesta pueda abrir un vínculo a donde tengas un catálogo de ramo.

Hasta ahora, sólo sería la posiblidad de que el tipo de pregunta agregada reconozca hipervínculos.

**Comment by elcoruco** [comment]
Los links se pueden agregar como descripción antes o después de la pregunta
