### ISSUE TITLE
El csv que se descarga de datos abiertos viene con caracteres extraños en lugar de acentos

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#131]
@elcoruco te dejo una pantalla.

![image](https://cloud.githubusercontent.com/assets/17733942/15132742/5edcfad6-1622-11e6-8ead-11cd378689ad.png)

**Comment by elcoruco** [comment]
Como te comenté un montón de veces, es Excel el que no le gustan los CSV. Para abrirlo en excel, descarga el excel. Si lo vas a ocupar en otra cosa, entonces sí usa el CSV.
