### ISSUE TITLE
Encuesta INADEM y PROSPERA (Importante para visualización página)

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#135]
@elcoruco queremos que estas encuestas estén visibles para el lanzamiento de Tú Evalúas, ¿que se puede hacer al respecto? Estaría bueno hablarlo, si se necesita volver a cargar la encuesta y agustarla a los tipos de preguntas pues yo lo puedo hacer, solo ocuparía que me digas qué onda.

**Comment by elcoruco** [comment]
Pues requieren cierta optimización para la página de resultados (tarda varios segundos en generar el reporte en tiempo real); pero ya quedó
