### ISSUE TITLE
Sección de Encuestas

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#137]
@hugovom en esta sección realmente es quitar el footer de equipo y participantes y poner tamaño h2 en en título de la encuesta para homologarlo con los titulos de la pagina.

Screenshoot:
![image](https://cloud.githubusercontent.com/assets/18603729/15295086/73e13a64-1b54-11e6-90a6-18dc8e1ca6f6.png)

**Comment by Victordeleon** [comment]
@hugovom si quieres deja esta para el final, jorge díaz nos está haciendo una revisión en esta parte.

**Comment by julioaleman** [comment]
Me comenta Víctor que si podrías también poner el recuadro que aparece cuando no contestas una pregunta obligatoria en un cuestionario de color rojo #D0021B y que la leyenda que aparece diga "Este campo es obligatorio"

**Comment by Victordeleon** [comment]
@hugovom ya podemos darle a esta parte, tomando en cuneta el comentario de @julioaleman por favor.
