### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#138]
@hugovom @elcoruco esta vista se estaria convirtiendo en el home page de la página, incluiria el banner y el filtro de resultados mas un cambio en la forma de presentar los resultados: una tabla.
Screenshoots:
![image](https://cloud.githubusercontent.com/assets/18603729/15295127/abbe9dd2-1b54-11e6-981b-6afb48fe3cdb.png)

![image](https://cloud.githubusercontent.com/assets/18603729/15295180/f7db6b3c-1b54-11e6-907d-d8020758f93b.png)

Código
Banner:
`<div class="video-banner" style="width: 100%; max-width: 100%; height: 470px; background: grey url(img/bannerTuEvaluas_2.png) no-repeat center center; background-size: cover; padding: 0 !important;">
					<div class="video-container" id="videoContainer" style="padding-bottom: 0;"></div>
					<div class="video-banner vplay" id="videoBannerPlay">
						
					</div>
				</div>`

Filtro (es el mismo que estaba en la sección de resultados que por cierto desaparece de el submenú):
`<div class="bottom-buffer">
                <div class="col-md-8">
                    <div class="panel-group ficha-collapse" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-parent="#accordion" data-toggle="collapse" href="#panel-01" aria-expanded="true" aria-controls="panel-01">
                                    Filtrar
                                    </a>
                                </h4>
                                <button type="button" class="collpase-button collapsed" data-parent="#accordion" data-toggle="collapse" href="#panel-01"></button>
                            </div>
                                <div class="panel-collapse collapse in" id="panel-01">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-2">Busca por atención: </div>
                                            <div class="col-md-10">
                                                <input class="form-control" placeholder="Palabra clave" type="text">
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <select class="form-group" name="category" id="survey-category">
								  					<option value=""> Selecciona una categoría </option>
                                                </select>
                                            </div>
                                            <div class="col-md-3">
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Subcategoría<span class="caret"></span></a>
                                            </div>
                                            <div class="col-md-3">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Etiquetas<span class="caret"></span></a>
                                            </div>
                                        </div>        
                                        <hr>
                                        <div class="bottom-buffer">
                                            <div class="pull-left">
                                                <button type="button" class="btn btn-primary">Filtrar resultados</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                    </div>
				</div>`

Tabla con paginación:
`<div class="col-md-8">
            				    <table class="table table-striped table-hover">
                                    <thead>
                                      <tr>
                                        <th>Nombre</th>
                                        <th>Dependencia</th>
                                        <th>Estatus</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <tr onclick="location='resultados.html'">
                                        <td>Premio Nacional de la Juventud 2016</td>
                                        <td>IMJUVE</td>
                                        <td>Abierta</td>
                                      </tr>
                                      <tr>
                                        <td>Fondos Sectoriales CONACYT: Encuesta de Satisfacción</td>
                                        <td>CONACYT</td>
                                        <td>Abierta</td>
                                      </tr>
                                      <tr>
                                        <td>Programa de Inclusión Social</td>
                                        <td>PROSPERA</td>
                                        <td>Cerrada</td>
                                      </tr>
                                      <tr>
                                        <td>Fondos Sectoriales CONACYT: Encuesta de Satisfacción</td>
                                        <td>SEDESOL</td>
                                        <td>Cerrada</td>
                                      </tr>
                                      <tr>
                                        <td>Instituto Nacional del Emprendedor</td>
                                        <td>INADEM</td>
                                        <td>Cerrada</td>
                                      </tr>
                                    </tbody>
                                </table>
                						<ul class="pagination">
                							<li><a href="#">&laquo;</a></li>
                							<li><a href="#">1</a></li>
                							<li><a href="#">2</a></li>
                							<li><a href="#">3</a></li>
                							<li><a href="#">4</a></li>
                							<li><a href="#">5</a></li>
                							<li><a href="#">&raquo;</a></li>
                						</ul>
			      </div>`

**Comment by hugovom** [comment]
@julioaleman no viable, en cuanto a costos, implementar el buscador en el home

**Comment by julioaleman** [comment]
A que te refieres con costos?

**Comment by Victordeleon** [comment]
Que tal @hugovom ya le había comentado sobre esto a @elcoruco y me dijo que no era mucho problema.
