### ISSUE TITLE
Sección Datos abiertos

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#141]
En esta sección seria replicar el buscador de resultados del home page con cambios en el texto del botón y cambiar la forma de ver los enlaces para descarga de datos abiertos, mostrarlos como tabla:

Screenshoots:
![image](https://cloud.githubusercontent.com/assets/18603729/15296094/5a2123be-1b59-11e6-89a6-decc75c796e9.png)

![image](https://cloud.githubusercontent.com/assets/18603729/15296099/5e47b642-1b59-11e6-8801-38c14a80ca42.png)

Codigo.
Filtro:
`<div class="col-md-8">
                    <div class="panel-group ficha-collapse" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-parent="#accordion" data-toggle="collapse" href="#panel-01" aria-expanded="true" aria-controls="panel-01">
                                    Filtrar
                                    </a>
                                </h4>
                                <button type="button" class="collpase-button collapsed" data-parent="#accordion" data-toggle="collapse" href="#panel-01"></button>
                            </div>
                                <div class="panel-collapse collapse in" id="panel-01">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-2">Busca por atención: </div>
                                            <div class="col-md-10">
                                                <input class="form-control" placeholder="Palabra clave" type="text">
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <select class="form-group" name="category" id="survey-category">
								  					<option value=""> Selecciona una categoría </option>
                                                </select>
                                            </div>
                                            <div class="col-md-3">
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Subcategoría<span class="caret"></span></a>
                                            </div>
                                            <div class="col-md-3">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Etiquetas<span class="caret"></span></a>
                                            </div>
                                        </div>        
                                        <hr>
                                        <div class="bottom-buffer">
                                            <div class="pull-left">
                                                <button type="button" class="btn btn-primary">Filtrar datos</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                    </div>`

Tabla con paginación:
`<div class="col-md-8">
            				    <table class="table table-striped">
                                    <thead clas="thead-default">
                                      <tr>
                                        <th>Nombre</th>
                                        <th>Dependencia</th>
                                        <th>Descarga</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <tr>
                                        <td>Premio Nacional de la Juventud 2016</td>
                                        <td>IMJUVE</td>
                                        <td>
                            	    		<a class="btn btn-link btn-sm" style="color:#545454;" href="http://www.tuevaluas.com.mx/csv/premio-nacional-de-la-juventud-2016.xlsx">XLSX</a>
                            	    		<a class="btn btn-link btn-sm" style="color:#545454;" href="http://www.tuevaluas.com.mx/csv/premio-nacional-de-la-juventud-2016.csv">CSV</a>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td>Fondos Sectoriales CONACYT: Encuesta de Satisfacción</td>
                                        <td>CONACYT</td>
                                        <td>
                                            <a class="btn btn-link btn-sm" style="color:#545454;">XLSX</a>
                            	    		<a class="btn btn-link btn-sm" style="color:#545454;">CSV</a>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td>Programa de Inclusión Social</td>
                                        <td>PROSPERA</td>
                                        <td>
                                            <a class="btn btn-link btn-sm" style="color:#545454;">XLSX</a>
                            	    		<a class="btn btn-link btn-sm" style="color:#545454;">CSV</a>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td>Fondos Sectoriales CONACYT: Encuesta de Satisfacción</td>
                                        <td>SEDESOL</td>
                                        <td>
                                            <a class="btn btn-link btn-sm" style="color:#545454;">XLSX</a>
                            	    		<a class="btn btn-link btn-sm" style="color:#545454;">CSV</a>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td>Instituto Nacional del Emprendedor</td>
                                        <td>INADEM</td>
                                        <td>
                                            <a class="btn btn-link btn-sm" style="color:#545454;">XLSX</a>
                            	    		<a class="btn btn-link btn-sm" style="color:#545454;">CSV</a>
                                        </td>
                                      </tr>
                                    </tbody>
                                </table>
                						<ul class="pagination">
                							<li><a href="#">&laquo;</a></li>
                							<li><a href="#">1</a></li>
                							<li><a href="#">2</a></li>
                							<li><a href="#">3</a></li>
                							<li><a href="#">4</a></li>
                							<li><a href="#">5</a></li>
                							<li><a href="#">&raquo;</a></li>
                						</ul>
			          </div>`

**Comment by hugovom** [comment]
@elcoruco :neckbeard:
