### ISSUE TITLE
Gráficas de Resultados de encuestas

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#142]
@hugovom y @elcoruco En las gráficas de los resultados de las encuestas, se tiene la propuesta de que aparezcan con una funcion donde la respuesta con mayor recurrencia se pinte azul #4D92DF, la menos recurrente rojo #D0021B y las demas en gris #DDDDDD, pero como sé que esto conlleva muchos costos en su defecto todas las barras se mostrarían en gris #DDDDDD como se muestra a continuación:

Propuesta:
![image](https://cloud.githubusercontent.com/assets/18603729/15296362/b433eea8-1b5a-11e6-9a17-ea3332b10097.png)

Por defecto:
![image](https://cloud.githubusercontent.com/assets/18603729/15296379/cb54d7b4-1b5a-11e6-9034-29b6ca2ade71.png)

**Comment by hugovom** [comment]
:joy: :joy: :joy: no es muy costoso, simplemente se acabó el presupuesto

**Comment by julioaleman** [comment]
Solo como comentario porque se ve en los screenshoots, todos los textos deben estar lo mas que se pueda alineados con el logo de gob.mx del header dinámico.
