### ISSUE TITLE
Envío de encuestas: no están llegando a mails de Hacienda (Importante)

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#146]
Hola @elcoruco acabo de notar que las encuestas no están llegando a mails de hacienda (a hotmails, gmails y eso si), no sé si esto se extienda a mails que sean de gob.mx.

Saludos,

**Comment by elcoruco** [comment]
Eso se debe a los filtros que aplica el servidor de correo de hacienda. En este caso, no se puede hacer nada.

**Comment by Victordeleon** [comment]
Pero esto es reciente @elcoruco yo siempre pude enviar correos a Hacienda, me llama la

**Comment by elcoruco** [comment]
Es un api vic, no hay código distinto para cuando es gmail o de Hacienda. Y la única razón, hasta hoy, por la que no llegan los correos a una dirección, es porque están bloqueados lo servidores de correo que reciben.

<img width="941" alt="screen shot 2016-05-17 at 5 26 49 pm" src="https://cloud.githubusercontent.com/assets/3756555/15341492/a1fa6d84-1c54-11e6-9b3d-67d576bdf5d5.png">

<img width="942" alt="screen shot 2016-05-17 at 5 26 01 pm" src="https://cloud.githubusercontent.com/assets/3756555/15341495/a57efb32-1c54-11e6-9d63-bd8add40141a.png">


este es el tipo de logs que se generan, y que podrían ver, si fuera su cuenta de mailgun.

**Comment by hugovom** [comment]
@Victordeleon 
![screen shot 2016-05-17 at 5 30 42 p m](https://cloud.githubusercontent.com/assets/2445854/15341637/7ebada38-1c55-11e6-9ec9-f01a2e66a53b.png)
