### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#149]
Es solo un style para que aparezcan homologadas con las opciones de ¿Que es? Datos Abiertos y FAQS:

Antes:
![image](https://cloud.githubusercontent.com/assets/18603729/15333971/9e6a7a4c-1c31-11e6-8c24-c158cd3314c2.png)

Despues:
![image](https://cloud.githubusercontent.com/assets/18603729/15333999/bfbcf5c6-1c31-11e6-943f-5f71b4759d88.png)

Codigo:
`<div class="navegador">
				<nav class="navbar navbar-inverse sub-navbar navbar-fixed-top">
  					<div class="container">
    					<div class="navbar-header">
      						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#subenlaces">
        						<span class="sr-only">Interruptor de Navegación</span>
        						<span class="icon-bar"></span>
                            	<span class="icon-bar"></span>
                            	<span class="icon-bar"></span>
                          	</button>
                          	<a class="navbar-brand" href="index.html" style="text-transform:Capitalize;">Tú Evalúas</a>
    					</div>
    					<div class="collapse navbar-collapse" id="subenlaces">
      						<ul class="nav navbar-nav navbar-right">
                                <li><a href="que-es.html">¿Qué es?</a></li>
                                <li><a href="datos-abiertos.html">Datos Abiertos</a></li>
                                <li><a href="preguntas-frecuentes.html">Preguntas Frecuentes</a></li>
                            </ul>
                        </div>
                	</div>
            	</nav>
        	</div>`

**style="text-transform:Capitalize;"**

**Comment by hugovom** [comment]
@julioaleman sabe gob.mx que su solicitud es contraria a lo que su
![screen shot 2016-05-23 at 10 26 44 a m](https://cloud.githubusercontent.com/assets/2445854/15475685/e16c25f4-20d0-11e6-916a-d7c26ed7e848.png)
 gráfica base dice?

**Comment by julioaleman** [comment]
De hecho ellos lo pidieron así, de hecho ya todo esta revisado por ellos.


Saludos


________________________________
De: Hugo Osorio <notifications@github.com>
Enviado: lunes, 23 de mayo de 2016 10:27 a. m.
Para: GobiernoFacil/tu-evaluas
Cc: julioaleman; Mention
Asunto: Re: [GobiernoFacil/tu-evaluas] Submenu (#149)


@julioaleman<https://github.com/julioaleman> sabe gob.mx que su solicitud es contraria a lo que su
[screen shot 2016-05-23 at 10 26 44 a m]<https://cloud.githubusercontent.com/assets/2445854/15475685/e16c25f4-20d0-11e6-916a-d7c26ed7e848.png>
gráfica base dice?

-
