### ISSUE TITLE
Se están utilizando números negativos en la encuesta de Conacyt

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#152]
La opción númerica te permite poner números negativos, quizá valdría la pena limitarla para evitar que se afecten las cifras relativas a mínimo, máximo y promedio.

**Comment by elcoruco** [comment]
bueno, limitar los número negativos, supongo que dependería del tipo de pregunta. 

En todo caso, sería bueno tener algún tipo de slider cuando se limite por rango. (No veo razón para no aceptar números negativos en un campo numérico).

Se agrega a la lista de "sería bueno tener"
