### ISSUE TITLE
Buscador en Tú Evalúas (Importante para visualización página)

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#157]
Que tal @elcoruco en el buscador que está en la sección de resultados de Tú Evalúas el botón de "Filtra por Resultados" no está haciendo nada, no pasa nada cuando lo picas.

**Comment by elcoruco** [comment]
era un error de la gráfica base. En un formulario, se utiliza un submit, no un botón. Ya lo arregló hugo.
