### ISSUE TITLE
Validacion de campos obligatorios en encuestas

### ISSUE THREAD

**Issue by julioaleman** [GobiernoFacil/tu-evaluas#165]
@hugovom me comento @Victordeleon que no se agrego el comentario mencionado en el issue #137 : "Me comenta Víctor que si podrías también poner el recuadro que aparece cuando no contestas una pregunta obligatoria en un cuestionario de color rojo #D0021B y que la leyenda que aparece diga "Este campo es obligatorio" para cada campo dependiendo:

Ahora se muestra:
![image](https://cloud.githubusercontent.com/assets/18603729/15523092/62c1fe78-21dd-11e6-947f-3852a54e50c8.png)

Se requiere:
![image](https://cloud.githubusercontent.com/assets/18603729/15523111/903a446e-21dd-11e6-8652-4e8518ac68d7.png)

**Comment by hugovom** [comment]
Deja lo checo y te aviso

**Comment by elcoruco** [comment]
bueno, se me hace un poquito demasiado poner el recuadro y el texto de que es obligatorio. De hecho, el hacer obligatoria una pregunta, en un cuestionario que no es obligatorio, hace un poco molesto el proceso. Yo creo que este sí queda fuera de la lista de issues.

**Comment by Victordeleon** [comment]
Boris, esta funcionalidad ya existe, el issue solo es para cambiar el color y el mensaje del recuadro. Entiendo que es un poco molesto, pero al presente no podemos controlar la obligatoriedad por pregunta, y si no te hace responder todo en la sección arriesgaríamos mucho la lógica de las encuestas que no tengan reglas de navegación.
