### ISSUE TITLE
Extracción de metadatos

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#167]
@hugovom @elcoruco En el requerimiento que les habíamos mandado viene bastante información, pero también sería muy bueno para nosotros si podemos realizar una extracción de la información por encuesta, como la que se guarda en la Tabla Bluprient. Así no sería necesario que se extraiga información de dos tablas diferentes... A nosotros nos gustaría poder extraer: 

-Nombre o id de la encuesta.
-Nombre de la persona que la creó.
-Nombre del ramo al que pertenece usuario.
-Nombre de la unidad responsable a la que pertenece usuario.
-Ramo de encuesta.
-Programa Presupuestario de encuesta.
-Categoría.
-Subcategorías.
-Etiquetas.

Pero la verdad, los más importente, sería el nombre o id de la encuesta, su ramo y su programa presupuestario. Solo sería para el Back End de Administrador.

**Comment by elcoruco** [comment]
se lo agregué a todos.
