### ISSUE TITLE
Mostrar Encuesta en Funcionarios Públicos. 

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#170]
@elcoruco me volviste a poner el botón de mostrar encuesta en la parte de funcionarios públicos (el que controla la visualización de la página).

También en relación a la carga de archivos con resultados en la sección de funcionarios públicos, también se debería solicitar a un administrador autorización para poder publicarlo, por lo que tampoco debe de tener el botón de mostrar encuesta.

**Comment by elcoruco** [comment]
mostrar u ocultar no publica la encuesta. es una tontería poner "cancelar" en lugar de ocultar.

**Comment by Victordeleon** [comment]
Entiendo @elcoruco ,  tienes razón en que sería una tontería cambiarlo por cancelar. Lo que quiero decir es que, en este momento, los usuarios de tipo "Funcionario PúbIlico", pueden controlar si una encuesta autorizada es visible en la página o no mediante la opción "Mostrar/Ocultar" encuesta. No creo que ello sea conveniente, ya que es muy fácil que se pongan a ocultarlas si no les gusta cómo se están dando los resultados, por lo que digo que esa opción se debería de quitar para funcionarios públicos y solo dejar su uso para administradores.

Lo mismo con la carga de archivos de resultados, a como esta en este momento, en cuanto carguen pueden publicar, yo opino que sería mejor que se tuviera que pedir la autorización, para controlar también que no suban cualquier ocurrencia.
