### ISSUE TITLE
Generación de Links

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#178]
@elcoruco No sé si fue algún problema del internet o tengamos un bug, pero no se me descargan 500 links de encuesta de un jalón, aunque si de a 100. 

Cuando trataba de a 500 me aparecía una pantalla de problema y no se descargaba el archivo, aunque si se contabilizaba como generado en los "generados" de la encuesta.

**Comment by elcoruco** [comment]
bueno, aquí el problema es el tiempo de ejecución. Cuando las claves se generaban con md5, un hash sencillo, el sistema podía generar montones de claves por segundo. Como eso no le gustó a los amigos de Gobmx, el hash ahora se genera con un método más complejo, que requiere mucho mayor tiempo de procesador.  Esto lleva a que el tiempo disponible de ejecución, no alcance para generar 500 claves. 

Lo que hice fue aumentar el número de segundos de ejecución, para que le de tiempo al sistema generar 500 claves. Pero le pondré un candado para que no puedas crear más de 500.
