### ISSUE TITLE
Poner Mayúscula y punto a mensaje de agradecimiento al final de una encuesta. 

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#179]
En la última pantalla que aparece cuando previsualizas o respondes una encuesta, solo habría que cambiar "gracias por participar en este estudio" por "Gracias por participar en este estudio".

![image](https://cloud.githubusercontent.com/assets/17733942/15902091/dea3cba4-2d6b-11e6-983e-945ed665dc80.png)

**Comment by elcoruco** [comment]
no mames vic
