### ISSUE TITLE
En la pestaña “Cuestionarios” cambiarlo por “Cuestionarios Públicos”

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#18]
Explicar qué es lo que se puede hacer en esta sección. “Podrás proponer y mandar alguna nueva pregunta a los cuestionarios públicos, también podrás descargar en CSV el id y correo de los cuestionarios así como los correos para respaldo o para utilizarlos en otras encuestas.

**Comment by hugovom** [comment]
Esta categoría se llamará envío de cuestionarios
