### ISSUE TITLE
Error en como se guardan las preguntas de opción múltiple varias (y su respectiva visualización en la página)

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#180]
@elcoruco ya está guardando bien si creas la encuesta desde la plataforma, pero el issue permanece si creas la encuesta cargando un archivo.

Este es el archivo que cargué:
[encuesta mas completa recopilacion.xlsx](https://github.com/GobiernoFacil/tu-evaluas/files/306158/encuesta.mas.completa.recopilacion.xlsx)

-Probé las encuestas generando links.
-Los errores se están dando en las preguntas de opción múltiple varias.
-Sin importar lo que respondas, siempre se guardan en la base o todas las opciones posibles o ninguna.
-El error se refleja en la visualización de la encuesta.

**Comment by hugovom** [comment]
@Victordeleon esto ya lo probamos y no encontramos error
