### ISSUE TITLE
Protocolo HTTPS no implementado

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#181]
@elcoruco 

La utilización del protocolo HTTPS en todos los elementos de la aplicación ofrece una comunicación segura y encriptada para ambas partes (servidor y cliente), haciendo que los datos que viajen de manera cifrada. Los protocolos SSL y TLS son fundamentales y deben ser las versiones 3.0 y 1.2 respectivamente, ya que son las más actuales, y contienen parches de seguridad recientes.
la aplicación se encuentra utilizando el protocolo HTTP, como se demuestra en su liga principal (http://www.gob.mx/tuevaluas/), así como otros elementos que contiene la aplicación. Al ser ésta una aplicación que se pretende instalar en la plataforma gob.mx, es altamente necesario se implemente el protocolo HTTPS y las versiones de SSL y TLS antes mencionadas.

**Comment by elcoruco** [comment]
el protocolo https requiere de certificados de seguridad que no tenemos ni podemos implementar. Esto lo debe hacer el admin del sistema.

**Comment by Victordeleon** [comment]
Que tal @elcoruco , ya negocié este tema con los de Gobmx y pues si quedaría la implementación del protocolo de su lado. Lo único que me piden es que se actualicen las librerías que se van a jalar del código para que incluya el https en su ruta, por que si no no funcionaría la implementación del protocolo, ¿Es algo dificil? ¿Te toma mucho tiempo? Me lo pedían para antes del lunes para poder hacer deploy temprano, ¿cómo ves?

**Comment by elcoruco** [comment]
TODAS las rutas son dinámicas, si no, solo serviría en un entorno (en en gob.mx o en tuevaluas.com.mx)
