### ISSUE TITLE
Posible exposición de rutas sensibles

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#183]
@elcoruco 

Exponer rutas que revelen información a los usuarios sobre la forma en que está estructurada la aplicación puede ayudar a que un usuario malintencionado planee y genere ataques elaborados a estas rutas sensibles. Se recomienda siempre no exponer estas rutas/directorios para evitar esto.
www.gob.mx/tuevaluas/tuevaluas/js/bower_components/jquery/dist/jquery.min.js
www.gob.mx/tuevaluas/index.php/js/bower_components/jquery/dist/jquery.min.js
La ruta sensible detectada en las ligas:
"/var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php

**Comment by elcoruco** [comment]
las rutas de bower ya no se ocupan. Todas las rutas están en github, que es público. La ruta que mencionan es parte del framework de laravel... parte de toooooodas las instalaciones de laravel.
