### ISSUE TITLE
Uso de captcha para inicio de sesión

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#184]
@elcoruco 

El uso de un captcha para el acceso a los aplicativos es siempre recomendado, ya que con estos se puede minimizar el riesgo de ataques de fuerza bruta o denegación de servicio, debido a que es necesaria la interacción de un usuario real para completar este sistema de seguridad.
En el formulario de acceso al aplicativo (login) no está implementado un sistema de seguridad (captcha).

**Comment by elcoruco** [comment]
Laravel utiliza penalizaciones de tiempo para cada intento de login fallido, así que no es necesario usar captcha para el login.
