### ISSUE TITLE
Uso de HTTP Athentication

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#186]
@elcoruco 

Como una medida de seguridad extra para la parte del login de usuarios, se recomienda implementar el uso de HTTP Authentication, debido a que trabajaría como una primera "capa" para el acceso a la aplicación.

Se recomienda se siga implementando en el  ingreso de usuarios administrador y funcionario  en el ambiente productivo y no solo en el ambiente de pruebas , debido a que ofrece una capa más de seguridad a la aplicación.

**Comment by elcoruco** [comment]
no, con las credenciales y el uso de https se podría evitar esto.
