### ISSUE TITLE
(1) Never use JavaScript 'history' object or navigation-based positioning functions

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#188]
@elcoruco 

Esta norma identifica cualquier uso del objeto "history" o funciones de posicionamiento basados en navegación. El uso de funciones de posicionamiento basados en navegación "history" (window.history, self.history) o (window.back (), window.forward ()) es una mala práctica por diferentes razones:
• POST: Si una página visitada se generó con POST, el navegador emitirá una advertencia si los datos presentados no están codificados en la URL.
• PRIVACIDAD: El uso del objeto "history" puede dar lugar a errores de navegación y va en contra de la privacidad del usuario.
• LÓGICA DE NAVEGACIÓN POBRES: La secuencia de páginas exacta que toma un usuario pueden no coincidir con las expectativas del programador. Por tales razones, es mucho mejor colocar al usuario en la URL exacta (usando ubicación), y permitir al usuario jugar con los botones de navegación del explorador si lo necesita.
Por tales razones, es mucho mejor colocar al usuario en la dirección URL exacta (usando la ubicación), y permitir al usuario jugar con los botones de navegación del explorador si se necesita.
trunk/public/js/main-built.js Line 45
[Source: 45]: }n=n||[] r=r||[] for(var u=n.length u-- )if(n[u]===e)return r[u]===t if(n.push(e) r.push(t) o)
{if(u=e.length u!==t.length)return!1 for( u-- )if(!D(e[u] t[u] n r))return!1}
else
{var l c=y.keys(e) if(u=c.length y.keys(t).length!==u)return!1 for( u-- )if(l=c[u] !y.has(t l)||!D(e[l] t[l] n r))return!1}
return n.pop() r.pop() !0} y.isEqual=function(e t)
{return D(e t)}
y.isEmpty=function(e)
{return null==e?!0:S(e)&&(y.isArray(e)||y.isString(e)||y.isArguments(e))?0===e.length:0===y.keys(e).length}
y.isElement=function(e)
{return!(!e||1!==e.nodeType)}
y.isArray=h||function(e)
{return"[object Array]"===f.call(e)}
y.isObject=function(e)
{var t=typeof e return"function"===t||"object"===t&&!!e}
y.each(["Arguments" "Function" "String" "Number" "Date" "RegExp" "Error"] function(e){y["is"+e]=function(t){return f.call(t)==="[object "+e+"]"}}) y.isArguments(arguments)||(y.isArguments=function(e)
{return y.has(e "callee")}
) "function"Unable to render embedded object: File (=typeof/./&&"object") not found.=typeof Int8Array&&(y.isFunction=function(e){return"function"==ty

**Comment by elcoruco** [comment]
Lo pinches mismo, ya lo comenté, pertenece al router de backbone.
