### ISSUE TITLE
(1) Do not allow to control the URL used in a redirect by an unvalidated input.

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#189]
@elcoruco 

No se debe permitir el control de una URL en una redirección sin validar. Al hacer esto puede favorecer a ataques PHISING. A través de redirecciones abiertas, usuarios maliciosos pueden atraer otros usuarios a visitar una URL confiable con una redirección a un sitio malicioso.
Violación
trunk/public/js/main-built.js line 45
}n=n||[] r=r||[] for(var u=n.length u-- )if(n[u]===e)return r[u]===t if(n.push(e) r.push(t) o)
{if(u=e.length u!==t.length)return!1 for( u-- )if(!D(e[u] t[u] n r))return!1}
else
{var l c=y.keys(e) if(u=c.length y.keys(t).length!==u)return!1 for( u-- )if(l=c[u] !y.has(t l)||!D(e[l] t[l] n r))return!1}
return n.pop() r.pop() !0} y.isEqual=function(e t)
{return D(e t)}
y.isEmpty=function(e)
{return null==e?!0:S(e)&&(y.isArray(e)||y.isString(e)||y.isArguments(e))?0===e.length:0===y.keys(e).length}
y.isElement=function(e)
{return!(!e||1!==e.nodeType)}
y.isArray=h||function(e)
{return"[object Array]"===f.call(e)}
y.isObject=function(e)
{var t=typeof e return"function"===t||"object"===t&&!!e}
y.each(["Arguments" "Function" "String" "Number" "Date" "RegExp" "Error"] function(e){y["is"+e]=function(t){return f.call(t)==="[object "+e+"]"}}) y.isArguments(arguments)||(y.isArguments=function(e)
{return y.has(e "callee")}
) "function"Unable to render embedded object: File (=typeof/./&&"object") not found.=typeof Int8Array&&(y.isFunction=function(e)
{return"function"==typeof e||!1}
) y****

**Comment by elcoruco** [comment]
esto ya lo comenté una vez. Este código pertenece al router de Backbone, que no estoy ocupando. Pero les valió vergas que se los comenté en gobtools.

**Comment by Victordeleon** [comment]
@elcoruco Me lo pdrás desarrollar un poco más para cerrar el bug y peleárselos  en la junta de mañana?

**Comment by Victordeleon** [comment]
@elcoruco lo reabrieron con este comentario

No se debe permitir el control de una URL en una redirección sin validar. Al hacer esto puede favorecer a ataques PHISING. A través de redirecciones abiertas, usuarios maliciosos pueden atraer otros usuarios a visitar una URL confiable con una redirección a un sitio malicioso.

Violación
public/js/lib/text.js

Líneas
17
18
19
20

**Comment by elcoruco** [comment]
Text.js es un plugin para cargar templates con requirejs. Obvio no lo voy a modificar.
