### ISSUE TITLE
Header X-Content-Type-Options:nosniff no detectado

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#190]
@elcoruco 
Esta es una característica de seguridad que ayuda a prevenir los ataques de sniffing basados en el tipo MIME ("Extensiones Multipropósito de correo de internet, por sus siglas en inglés). Este hallazgo se detecta en los headers de respuesta de la aplicación, es aquí donde debería mostrarse la utilización de este header para minimizar el riesgo de sniffing.

Se recomienda implementar este header en el aplicativo para minimizer el riesgo de ataques de sniffing tipo MIME. Un ejemplo de configuración de este header sería:

<IfModule mod_headers.c>
  Header set X-Content-Type-Options nosniff
</IfModule>

Y en la respuesta de la aplicación se observaría de esta manera:}

**Comment by elcoruco** [comment]
<img width="244" alt="screen shot 2016-06-30 at 7 17 31 pm" src="https://cloud.githubusercontent.com/assets/3756555/16508311/5db1125c-3ef7-11e6-80e6-0103bbf31e31.png">

listo, se agregó un middleware que agrega ese header
