### ISSUE TITLE
Header X-XSS-Protection no detectado

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#191]
@elcoruco 

La implementación de este header ayuda a minimizar el riesgo de ataque Cross.site Scripting siempre y cuando se configure de manera correcta. Este header rechaza los intentos de XSS en el navegador ofreciendo un bloqueo activo de estos. 

Un ejemplo de configuración sería el siguiente:

<ifModule mod_headers.c>
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
</ifModule>

Donde el número “1”, significa que está activa esta opción, y “mode=block” significa que el navegador bloqueará intentos de XSS.

**Comment by elcoruco** [comment]
<img width="253" alt="screen shot 2016-06-30 at 7 28 18 pm" src="https://cloud.githubusercontent.com/assets/3756555/16508470/d50a606e-3ef8-11e6-95a0-73e3271742c7.png">


listo. Aunque leí que eso de mode=block creaba una vulnerabilidad en IE8. Pero sepa
