### ISSUE TITLE
Cookie de sesión sin Secure Flag

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#192]
@elcoruco 

“Secure flag” es una opción que se puede configurar en el servidor de la aplicación cuando se envía una nueva cookie al usuario dentro de una respuesta HTTP. El propósito de esta opción es evitar que las cookies sean observadas por terceros no autorizados cuando se transmite por un canal de comunicación no encriptado.
Se detecta que el hallazgo de severidad Alta referente a la cookie de sesión se encuentra sin el atributo de secure flag.
Para que las cookies de sesión del aplicativo viajen de manera segura es recomendado implementar la opción “secure flag”. Esto hace que viaje de manera segura en la aplicación y no pueda ser interceptada por un usuario malicioso que pudiera estar “escuchando” la información que va desde el servidor a un usuario o viceversa.
Ejemplo de resolución:
Configurar en el servidor el atributo secure flag para las cookies:
<session-config>
<cookie-config>
<secure>true</secure>
</cookie-config>
</session-config>
Y en las respuestas del navegador se observaría lo siguiente:
Set-cookie:session=YlZtM3U1YkZablhkR2ZTNVQ1aEJvWFRTZmNna2VPb05iRU1XVlJEQ0VHeGZsbHQxWTRId2JHb3NNejNhRTZsSlhrRE81am5TenlTb0Q4S0JyTlRaNXRJVyswZ0pLRlZwdmFWdlpxaDhXL09LZnZLeHNNUWNpeTRBUEN5RUxZeFlubXBscE9kbEtWbHd2Wis2RzRXWGpGblUyangvb01WRnJlM3VOcGgwcmtoL253Uys1VTVoeTZuTTVJTEZSVjI5LS1KMjNPbVU0Z1ArMDdaY1NsUDZFeFlnPT0%3D--7d30b3bdee7dbee05b420746a2f0d3190835b017; path=/; secure; HttpOnly
Este atributo ayuda a mejorar la seguridad en conjunto con el atributo HttpOnly, por lo cual es considerado que se usen en conjunto.

**Comment by elcoruco** [comment]
Esto lo cambio cuando ya estemos en https, porque si no, nos fastidia un poquito.

**Comment by Victordeleon** [comment]
Ya estamos en https

**Comment by elcoruco** [comment]
en el servidor de nosotros... no en el de ellos. 

de todos modos ya quedó.
