### ISSUE TITLE
Cookie de sesión sin HttpOnly flag

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#193]
Si la bandera HttpOnly está incluido en el encabezado de respuesta HTTP, la cookie no se puede acceder a través de script del lado del cliente (de nuevo si el navegador es compatible con esta bandera). Se detecta en la respuesta HTTP que esta opción no está habilitada para la cookie de sesión.

Esta opción ayuda a proteger las cookies de sesión de lectura y escritura por parte de scripts de usuarios maliciosos, minimizando así el riesgo de que puedan ser robadas por estos usuarios.

@elcoruco 
Un ejemplo de configuración sería el siguiente:

<session-config>
 <cookie-config>
  <http-only>true</http-only>
 </cookie-config>
</session-config>

Y en la respuesta de la aplicación se vería de esta forma:

Set-Cookie:ahoy_visit=453883db-b14e-4690-bbc4-2a8bfefa9162; path=/; expires=Sun, 19 Jun 2016 00:07:20 -0000
Set-Cookie:_consul_session=WWFSWEhMb0VlUnVOVzNvSGErNmJ2TzVZQmp2TzJGOXZ1b2I0RVZtbnRVRjRrSHZseVRBTFYwNElLRldZbEwyeXlpcWlpdDNPL1JKcys1YUgrZ2JBcnBLR2g1MFU3V2Z4OXg3cnRGNHBuRUV1MU8rLzRzVXpmVjB0dlZGYnBOay9PM2lsWlpuZlhDOXpDUm1IdE1jYXVmajB0enFpb3VGZUx3WjBHWWtFekNrPS0tVTBYNjkrMW4ya3hoazJuSkNFNXRNZz09--8b725a7391f300400f36575eb2b0f2faecccd40f; path=/; HttpOnly

**Comment by elcoruco** [comment]
<img width="729" alt="screen shot 2016-06-30 at 6 45 41 pm" src="https://cloud.githubusercontent.com/assets/3756555/16507865/f69929fa-3ef2-11e6-8797-045196342b78.png">

<img width="1064" alt="screen shot 2016-06-30 at 6 49 46 pm" src="https://cloud.githubusercontent.com/assets/3756555/16507925/7b579794-3ef3-11e6-85fa-99cd162fd2ef.png">

la configuración de http only sí está habilitada. SIEMPRE ESTUVO HABILITADA. :/

**Comment by elcoruco** [comment]
(se llama laravel_session la cookie de la sesión)
