### ISSUE TITLE
No se visualiza el banner en el login de funcionario/Admin

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#195]
![image](https://cloud.githubusercontent.com/assets/17733942/17684010/6e87fd94-631d-11e6-8432-e295f1a31413.png)

**Comment by elcoruco** [comment]
![captura de pantalla 2016-08-16 a las 10 13 11 a m](https://cloud.githubusercontent.com/assets/3756555/17704236/161b49b8-639a-11e6-8782-f6b8eca9f10b.png)

puede que sea el detalle con el https, como dicen. Porque en otro entorno, sí funciona.
