### ISSUE TITLE
El título en el navbar debe estar en altas y bajas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#196]
![image](https://cloud.githubusercontent.com/assets/17733942/17684038/c2f49d88-631d-11e6-9940-a6623d25dac0.png)

**Comment by elcoruco** [comment]
![captura de pantalla 2016-08-16 a las 10 31 54 a m](https://cloud.githubusercontent.com/assets/3756555/17705089/bcf8c2c2-639c-11e6-85ce-db1a677efd3e.png)

El título está en altas y bajas, pero la gráfica base modifica esto.

![captura de pantalla 2016-08-16 a las 10 32 13 a m](https://cloud.githubusercontent.com/assets/3756555/17705102/cbb5ab04-639c-11e6-9686-710aa9bc5da1.png)
