### ISSUE TITLE
Carga de archivos con formato distinto al pre-establecido

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#198]
La aplicación, ya una vez iniciado sesión en la parte del login, contiene campos en los cuales se pueden cargar encuestas o listas de correos utilizando un formato de Excel, pero es posible cargar archivos con otro formato de archivos y de diferentes tamaños, como un .bat o .exe, lo cual es incorrecto. Se recomienda utilizar validaciones a nivel front y back sobre el formato y peso de los archivos que se estén cargando al sistema.
Esta acción podría realizarse solamente si un usuario traspasa las medidas de seguridad implementadas en el login, donde no se permite la entrada de datos como cadenas de código y además está presente la la seguridad dada por DosArrest y Akamai, los cuales previenen las peticiones masivas de unas mismas direcciones IP.

**Comment by elcoruco** [comment]
hay cualquier cantidad de formatos para subir archivos de encuestas. si tienen un whitelist, que rolen

**Comment by elcoruco** [comment]
pues nunca hubo whitelist

**Comment by Victordeleon** [comment]
Van las cargas:

Selecciona portada (Crear encuesta en la plataforma, Crea encuesta desde un archivo y Publicar archivo con resultados): PNG, JPEG.

Crea una encuesta desde un archivo: XLSX.

Publica un archivo con resultados: XLSX y CSV.

Envía la invitación a una lista de correos: XLSX.
