### ISSUE TITLE
Poner el HTTPS

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#199]
Las plantillas de estilo no se están implementando en Gob.Mx en teoría es por lo de que no tienen https las ligas. Así es como se ve orita el Dashboard de funcionario/Administrador

![image](https://cloud.githubusercontent.com/assets/17733942/17684303/0edbd552-6320-11e6-8f1e-979b7c59919d.png)

**Comment by elcoruco** [comment]
El https se pone automático en las rutas. Solo necesita que en su variable de entorno esté bien la ruta de carga de los archivos. [ es decir, que en lugar de cargar todo desde / se cargue desde /tuevaluas ]
