### ISSUE TITLE
Previsualización de preguntas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#201]
Qué tal @elcoruco 

Ya hablé bien con la gente de GobMx y después del tema del https ya no hay problemas en el guardado de las preguntas, la cosa más bien es que solo las preguntas de tipo opción multiple o varias no están apareciendo en la previsualización, te anexo una pantalla:

![image](https://cloud.githubusercontent.com/assets/17733942/18691453/555137fc-7f59-11e6-98d5-e5c0003c1801.png)

Me comentan que estos fueron los cambios que hicieron al código

|--------------------------------------------------------------------------
  | HTTPS Only Cookies
  |--------------------------------------------------------------------------
  |
  | By setting this option to true, session cookies will only be sent back
  | to the server if the browser has a HTTPS connection. This will keep
  | the cookie from being sent to you if it can not be done securely.
  |
  */

  'secure' => false,

  /*
  |--------------------------------------------------------------------------
  | HTTP Access Only
  |--------------------------------------------------------------------------
  |
  | Setting this value to true will prevent JavaScript from accessing the
  | value of the cookie and the cookie will only be accessible through
  | the HTTP protocol. You are free to modify this option if needed.
  |
  */

  'http_only' => false,

[5:40]  
y permisos en una carpeta

[5:40]  
para subir los archivos de encuestas

**Comment by elcoruco** [comment]
pues ya reinstalé de cero todo el sitio, y no tiene ese problema. Creo que deberían simplemente borrar todo lo que tienen, y hacer una nueva instalación, aprovechando que agregué la funcionalidad de bloquear encuestas una vez que terminaron

**Comment by elcoruco** [comment]
pues sepa qué pasa.
