### ISSUE TITLE
Base de datos con información sobre datos personales

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#202]
@elcoruco se implementó correctamentela parte de datos personales para el envío de preguntas, su visualización en el front end y la descarga en datos abiertos. Sin embargo, ya nunca se terminó el desarrollo que permitiría descargar, solo desde el back end, una base de datos que incluya la información de datos personales.

**Comment by elcoruco** [comment]
Ya está, aunque si no es https, chrome lo identifica como sitio no seguro. Para descargar datos personales en viejas encuestas, hay que generar los archivos nuevamente.
