### ISSUE TITLE
Publicar un archivo con resultados

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#203]
Actualmente, cuando se carga un archivo mediante la opción "Publica un archivo con Resultados" para la sección de Datos Abiertos, la liga para descargar el archivo aparece como "Archivo con Resultados". De este modo, habría que cambiar la liga para que muestre el formato del archivo que fue cargado, como por ejemplo xlsx, csv, pdf....

**Comment by elcoruco** [comment]
En Osx, por ejemplo, los archivos no están obligados a tener extensión. Este es un feature ocioso.
