### ISSUE TITLE
Visualización de encuestas enviadas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#204]
Las funcionarios que respondieron la encuesta del Diagnóstico sobre la recopilación de información sobre satisfacción ciudadana reportaron en varias ocasiones, tanto en Chrome como en Explorer, la primera vez que abrieron la liga para responder la encuesta no pudieron visualizar las preguntas. De este modo, para poder verlas tuvieron que dar refresh al navegador, lo que les daba la impresión de que el navegador no funcionaba.

**Comment by elcoruco** [comment]
comprimí todo en un solo archivo, más que eso no se puede hacer
