### ISSUE TITLE
Envío de encuestas por medio de una lista de correos

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#210]
@elcoruco 

Esto solo está pasando en Gob.Mx pero te lo comento por si se te ocurre que podría ser... cuando mandas una encuesta por medio de una lista de correos si la reciben los usuarios. Sin embargo, la liga está quebrada y te marca pantalla de error.

**Comment by Victordeleon** [comment]
@elcoruco 

Chequé como están las ligas y parece que no es una cuestión del Protocolo:

- Este es un ejemplo de liga enviado mediante una lista de correos: https://www.gob.mx/encuesta/$2y$10$Wl28qpTCajrviUdXH8TEIeU9sgOHUC47yPwLJDgYDvBssP6qzIDU6

- Este es un ejemplo de liga enviado a un correo individual (que sí funciona):

https://www.gob.mx/tuevaluas/encuesta/$2y$10$LFYjJ19xkP6RPD3uIL.4v.inNBnu1.abVTmOPF4RNb.Y2Qwzts0c6

Parece que la diferencia radica en que el de la liga de una lista de correos no trae el /tuevaluas

**Comment by elcoruco** [comment]
![captura de pantalla 2016-12-12 a la s 00 16 31](https://cloud.githubusercontent.com/assets/3756555/21089743/446649ea-c000-11e6-987c-2963eccf1be5.png)

hice la prueba desde docker, y si está bien configurada la variable de APP_URL=http://0.0.0.0/tuevaluas/ los links se generan de manera correcta
