### ISSUE TITLE
Los 3 issues que quedaron

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#213]
@elcoruco lo que te comentaba:

1. Que aparezcan las reglas de navegación.
2. Checar que en la búsqueda de usuario no se le pueda dar enter.
3. ´Poner lock para que se pueda descargar un máximo de 500 ligas.

**Comment by elcoruco** [comment]
pues ya lo revisé, y ya pifa en todos los ambientes
