### ISSUE TITLE
Liga de encuestas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#214]
Hola @elcoruco 

Persistió este problema en el pase a producción:

Cuando envías encuestas por medio de un correo adjunto, no se está mandando la liga completa. En el mail que recibo la liga está apareciendo así:
https://www.gob.mx/encuesta/$2y$10$dWzyc2os4A4Y4vMiKDsuuVkICiOtCv3yTXhYE4f2zKSkIBaMqra

La cual te da pantalla de error. Básicamente le falta agregar /tuevaluas después de /encuesta para que quede así:

https://www.gob.mx/encuesta/tuevaluas/$2y$10$dWzyc2os4A4Y4vMiKDsuuVkICiOtCv3yTXhYE4f2zKSkIBaMqra

La cual ya te da la liga correcta.

**Comment by elcoruco** [comment]
![Uploading Captura de pantalla 2017-02-12 a la(s) 21.51.51.png…]()


desde docker

**Comment by elcoruco** [comment]
/tuevaluas/encuesta/key...

**Comment by elcoruco** [comment]
![captura de pantalla 2017-02-12 a la s 21 51 51](https://cloud.githubusercontent.com/assets/3756555/22870574/e7cbf3e8-f16d-11e6-812b-70b7ea325a9e.png)

**Comment by Victordeleon** [comment]
@elcoruco esto solo pasa cuando mandas el correo por medio de un excel, ¿así lo probaste?
