### ISSUE TITLE
Descarga de Archivos con Resultados

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#216]
aSe encontró es que, una vez cargado el archivo (En la opción de Publicar una encuesta con resultados), el nombre del archivo de descarga no corresponde con el que fue cargado. 

![image](https://cloud.githubusercontent.com/assets/17733942/22702291/d4f39420-ed25-11e6-9b1b-7e5ef8a92eb0.png)

![image](https://cloud.githubusercontent.com/assets/17733942/22702308/e2b2243c-ed25-11e6-94e2-d3292e23dd06.png)

Se podrá modificar para que tenga el mismo nombre que el archivo que fue cargado?

**Comment by elcoruco** [comment]
sí pues sí. Se generan los nombres para que no se dupliquen, para que no suban tarugadas, para que no metan caracteres raros, y demás chismes
