### ISSUE TITLE
Carga de Archivos con Resultados

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#217]
@elcoruco 

Publica encuesta con resultados debe admitir la carga de csv y xlsx, sin embargo, no me está permitiendo cargar CSV. 

![image](https://cloud.githubusercontent.com/assets/17733942/22702511/9c8b697c-ed26-11e6-971d-addfba7f06af.png)

**Comment by elcoruco** [comment]
Listo. Algunos servidores identifican los archivos csv como de texto. Agregué "text/plain" al validador.
