### ISSUE TITLE
Envío de encuestas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#218]
@elcoruco 

La funcionalidad de refrescar encuestas está operando correctamente, sin embargo, ahora me está permitiendo avanzar de secciones sin contestar todas las preguntas.
Se necesita que todas las respuestas sean obligatorias por sección (así como estaba antes) ya que de lo contrario no funcionarán correctamente las reglas de navegación.

**Comment by elcoruco** [comment]
listo
