### ISSUE TITLE
Envío de encuestas masivas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#219]
@elcoruco 

Estuve hablando con Aura en relación al tema de el correo que se utilizará para el envío masivo de encuestas. Me comenta que ustedes prometieron que, en caso de tener un correo con envíos ilimitados, ya no habría necesidad de utilizar Mail Gunn. Ya contamos con ese correo (proporcionado por Hacienda) por lo que requerimos integrarlo a Tú Evalúas.

Quedo al pendiente.

**Comment by hugovom** [comment]
:frowning: :office: :office:
