### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#220]
Qué tal @elcoruco 

Los gob me siguen molestando con lo del autocomplete en el login. Me comentan que la vulnerabilidad persiste ya que el explorador te da la posibilidad de guardar la contraseña y que esto se debe quitar.

Se puede inhabilitar el guardado de la contraseña en el explorador?

![image](https://cloud.githubusercontent.com/assets/17733942/22893689/13f2f048-f1dc-11e6-9f71-9d3a483eb2d2.png)

**Comment by elcoruco** [comment]
<img width="684" alt="screen shot 2017-03-18 at 5 45 48 pm" src="https://cloud.githubusercontent.com/assets/3756555/24076913/c05edd2a-0c02-11e7-839d-6a009135b46e.png">


Al parecer, Chrome se pasa por el arco del triunfo lo de autocomplete=off, pero igual ya se lo agregué, por si luego cambian de opinión 😄
