### ISSUE TITLE
Posible exposición de rutas sensibles

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#221]
@elcoruco Me mantienen esto de posible exposición de rutas sensibles, ¿cómo lo ves?

Persiste el hallazgo ya reportado.
Durante el análisis se detecta una posible ruta sensible en el aplicativo, esta es la ruta de http://10.20.58.9/tuevaluas/web.config que no debería ser mostrada a los usuarios como medida de seguridad, ya que contiene puede contener información sensible y de utilidad para usuarios maliciosos.

**Comment by elcoruco** [comment]
<img width="437" alt="screen shot 2017-03-16 at 4 43 49 pm" src="https://cloud.githubusercontent.com/assets/3756555/24021693/c48ca446-0a67-11e7-810b-94a22819f849.png">

listo
