### ISSUE TITLE
Incorrecto manejo de errores

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#222]
@elcoruco 

Se detecta en el aplicativo que al intentar provocar un error manda un mensaje diciendo que la pagina no está disponible, la cual debería estar con un error mitigado.
Se recomienda que el aplicativo cuando mande mensajes de error se encuentren homologados.

**Comment by elcoruco** [comment]
<img width="761" alt="screen shot 2017-03-18 at 5 41 16 pm" src="https://cloud.githubusercontent.com/assets/3756555/24076880/1c8f7b8c-0c02-11e7-9d13-39c813b3e069.png">

listo
