### ISSUE TITLE
Ruby on rails

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#223]
@elcoruco como ves esto?

Ruby on Rails contiene un defecto en su diseño que puede permitir a los atacantes acceder más fácilmente aplicaciones. El problema se debe al mecanismo de CookieStore almacena cookies en el lado del cliente, aunque no es el mantenimiento de una entrada correspondiente en el lado del servidor. Cuando una aplicación termina una sesión, Ruby on Rails tiene ningún método para realizar un seguimiento de este e invalidar la cookie con la configuración por defecto de verdad. Esto significa que las cookies persisten "de por vida" y se pueden usar para acceder a una aplicación incluso después de que se cree que es terminada en muchos casos. 
Se declara en prioridad Baja debido a que no existe un inicio de sesión de usuarios en el aplicativo, pero consideramos importante su mención.
Es posible mitigar temporalmente el defecto mediante la aplicación de la siguiente solución: cambiar a un sistema de gestión de autenticación más seguros (por ejemplo ActiveRecordStore). Así mismo, es recomendable, actualizar la versión de rails de la aplicación si se tiene en alguna versión anterior a la más reciente y estable, ya que con los nuevos updates surgen parches y correcciones de seguridad para distintos aspectos de rails.

**Comment by elcoruco** [comment]
O____O

es PHP, no usamos Ruby x_____x
