### ISSUE TITLE
Permisos para administrador

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#27]
En el portal de "Administrador" habilitar funcionalidades que permitan:

- Publicar las encuestas que hayan sido creadas o cargadas.
- Ocultar temporalmente, de la página de www.tuevaluas.com, encuestas que ya hayan sido publicadas.

**Comment by hugovom** [comment]
@Victordeleon esta función si está habilitada para el administrador
![screen shot 2016-03-09 at 12 10 49 p m](https://cloud.githubusercontent.com/assets/2445854/13645306/fc189dae-e5ef-11e5-8659-1a3acdc35578.png)
