### ISSUE TITLE
Pendientes Tú Evalúas

### ISSUE THREAD

**Issue by Victordeleon** [GobiernoFacil/tu-evaluas#36]
Problemas que se están generando:
- Si tratas de realizar modificaciones en alguna encuesta y, posteriormente, la actualizas (tanto en el uso de subcategorías como en la carga de imágenes) te aparece pantalla de error.
- Los mensajes de error, que aparecen al querer actualizar la encuesta sin incluir al menos una subcategoría o etiqueta, se traslapan con el texto, por lo que no son legibles. También, dichos mensajes deben comenzar con mayúscula. 

Funcionalidades pendientes: 
- El formato de .csv para carga no está reconociendo signos de interrogación ni acentos. En uno de los casos (la primera pregunta de la prueba que les mande), me apareció como numérica cuando le había puesto text en el formato para carga.
- La opción "Crear encuesta" en el Dashboard sigue vinculada a "Mis encuestas". La idea de esta opción era que al seleccionarla pudieran crear directamente las encuestas. La idea es que en Crear encuesta, encuentres los tres recuadros para: crear encuesta nueva, crear encuesta desde un archivo y subir resultados de encuestas realizadas. En mis encuestas debería aparecer el histórico de las encuestas creadas con sus respectivos buscadores ya funcionales. 
- En la sección "Mis encuestas" de funcionarios públicos, el buscador no está funcionando.

Administradores
- Falta habilitar las autorizaciones para la publicación y el envío masivo de encuestas. También habilitar las notificaciones que permitan al administrador conocer la actividad de los funcionarios y las encuestas que se han terminado (sin necesidad de que revise una por una).
- También falta habilitar permisos para editar o cambiar encuestas que ya han sido terminadas.
- En "Todas las encuestas" falta habitar las búsquedas por categoría, subcategorías  y visitas. 

Homepage
- Falta vincular el programa de la encuesta con su ficha del programa en PTP.
- Crear sección de Datos Abiertos. 
- Crear sección de “Seguimiento de Encuestas” donde se pueda dar seguimiento de quejas (como subir un video desde el celular) y direccionarlas a la dependencia pertinente.

**Comment by hugovom** [comment]
@Victordeleon "Crear sección de “Seguimiento de Encuestas” donde se pueda dar seguimiento de quejas (como subir un video desde el celular) y direccionarlas a la dependencia pertinente." 
:open_mouth: esto no es posible

**Comment by hugovom** [comment]
@Victordeleon "Falta vincular el programa de la encuesta con su ficha del programa en PTP." cómo funciona esto?
