### ISSUE TITLE
Liga a  fichas de programas en Seguimiento de Evaluación del Desempeño del Portal de Transparencia Presupuestaria

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#43]
Con respecto a vincular la información las encuesta con sus fichas de PTP, la idea sería que se pudiera agregar un botón (que diga algo así como "Conoce más del programa en el Portal de Transparencia Presupuestaria) para cada encuesta que te vincule a las fichas de programas en Seguimiento de Evaluación del Desempeño del Portal de Transparencia Presupuestaria. Obviamente en este momento no se podrían poner las ligas porque todavía no tenemos las encuentas, pero se podría ir creando la funcionalidad y que nos especifiquen el código para nosotros poder poner la liga.

**Comment by hugovom** [comment]
https://github.com/GobiernoFacil/tu-evaluas/issues/54

**Comment by hugovom** [comment]
corregido
<img width="328" alt="screen shot 2016-04-05 at 12 16 38 a m" src="https://cloud.githubusercontent.com/assets/2445854/14271944/adaf5a84-fac3-11e5-8891-81d63b94a4f7.png">
