### ISSUE TITLE
Administrador: "Comparte tu opinión"

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#44]
Con respecto a lo de seguimiento para quejas, igual sería crear un botón para las encuestas (que diga algo como "Comparte tu opinión") que te abra una ventana para mandar correos. Todavía no podemos definir a quién iría dirigido, pero se podría crear la funcionalidad y dejarla oculta para después agregar los destinatarios. Sólo que nos especifiquen en dónde se encuentra en el código.

**Comment by hugovom** [comment]
@Victordeleon :confused:

**Comment by elcoruco** [comment]
Este feature tal vez en la siguiente versión
