### ISSUE TITLE
Si tratas de realizar modificaciones en alguna encuesta y, posteriormente, la actualizas (tanto en el uso de subcategorías como en la carga de imágenes) te aparece pantalla de error.

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#46]

**Comment by Victordeleon** [comment]
También hay que cambiar el botón por Actualizar Encuesta por Guardar cambios

**Comment by hugovom** [comment]
@Victordeleon lo del botón ya quedó: https://github.com/GobiernoFacil/tu-evaluas/issues/41

**Comment by Victordeleon** [comment]
@elcoruco Aquí solo faltaría que al guardar los cambios te quedes en el mismo editor.
