### ISSUE TITLE
Los mensajes de error, que aparecen al querer actualizar la encuesta sin incluir al menos una subcategoría o etiqueta, se traslapan con el texto, por lo que no son legibles. También, dichos mensajes deben comenzar con mayúscula.

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#47]

**Comment by Victordeleon** [comment]
![image](https://cloud.githubusercontent.com/assets/17733942/14287518/8ea0cc04-fb18-11e5-8d62-0fb3f65eaa36.png)

**Comment by hugovom** [comment]
@Victordeleon listo

**Comment by Victordeleon** [comment]
Yo todavía lo veo 

![image](https://cloud.githubusercontent.com/assets/17733942/14288084/e415a5fe-fb1a-11e5-8f64-241692034a96.png)
