### ISSUE TITLE
El formato de .csv para carga no está reconociendo signos de interrogación ni acentos

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#48]
En uno de los casos (la primera pregunta de la prueba que les mande), me apareció como numérica cuando le había puesto text en el formato para carga.

**Comment by Victordeleon** [comment]
@elcoruco ya estamos a punto de cerrar este tema, solo faltaba checar el tema de las preguntas de tipo opción múltiple (varias).
