### ISSUE TITLE
En "Todas las encuestas" falta habitar las búsquedas por categoría, subcategorías y visitas.

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#53]
El buscador en "Todas las encuestas" de funcionarios públicos todavía no tiene para también tiene que poder hacer búsquedas por categorías, subcategorías, etiquetas y número de visitas a las encuestas.

**Comment by hugovom** [comment]
> La Idea es que también se agreguen las columnas de visitas y envíos a las columnas de todas las encuestas, que el buscador se coloque por encima de las encuestas y que también realice las búsquedas por envíos y visitas.
@Victordeleon

**Comment by elcoruco** [comment]
buscar por número de visitas no está bien definido (y ya es posible buscar por categoría, subcategoría y etiquetas)
