### ISSUE TITLE
El buscador en "Todas las encuestas" de funcionarios públicos todavía no tiene para también tiene que poder hacer búsquedas por categorías, subcategorías, etiquetas y número de visitas a las encuestas.

### ISSUE THREAD

**Issue by ArgentinaVelasco** [GobiernoFacil/tu-evaluas#66]

**Comment by Victordeleon** [comment]
La Idea es que también se agreguen las columnas de visitas y envíos a las columnas de todas las encuestas, que el buscador se coloque por encima de las encuestas y que también realice las búsquedas por envíos y visitas.

**Comment by hugovom** [comment]
duplicado: #53
