### ISSUE TITLE
Corregir errores de pantalla que aparecen cuando tratas de enviar alguna encuesta sin poner alguna opción.

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/tu-evaluas#67]

**Comment by hugovom** [comment]
@Victordeleon tendrás algún screenshot?

**Comment by Victordeleon** [comment]
![image](https://cloud.githubusercontent.com/assets/17733942/14287038/ed68adbc-fb16-11e5-82eb-d1e6cdc6f5a0.png)
![image](https://cloud.githubusercontent.com/assets/17733942/14287087/16161aba-fb17-11e5-9602-ce78e79f6afa.png)
![image](https://cloud.githubusercontent.com/assets/17733942/14287112/2eb1ee64-fb17-11e5-9a1f-d27a9f6cb902.png)

**Comment by Victordeleon** [comment]
@hugovom Para ser más específcio, pasa cuando usas la opción de envío individual y no seleccionas una de las encuestas disponibles.
